### ISSUE TITLE
Have autotest.py create the buildlogs folder if it doesn't exist

### ISSUE THREAD

**Issue by gmorph** [diydrones/ardupilot#1731]
log list
HOLD> Requesting log list
Log 1  numLogs 2 lastLog 2 size 147456 Mon Jan  5 09:08:13 2015
Log 2  numLogs 2 lastLog 2 size 704512 Mon Jan  5 09:09:21 2015
log download latest /home/grant/3dr/buildlogs/APMrover2-log.bin
log download latest /home/grant/3dr/buildlogs/APMrover2-log.bin
HOLD> Downloading log 2 as /home/grant/3dr/buildlogs/APMrover2-log.bin
ERROR in command: [Errno 2] No such file or directory: '/home/grant/3dr/buildlogs/APMrover2-log.bin'
Traceback (most recent call last):
  File "/home/grant/.local/lib/python2.7/site-packages/MAVProxy-1.4.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 459, in process_stdin
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_log.py", line 180, in cmd_log
    self.log_download(log_num, filename)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_log.py", line 126, in log_download
    self.download_file = open(filename, "wb")
IOError: [Errno 2] No such file or directory: '/home/grant/3dr/buildlogs/APMrover2-log.bin'
^C^CTraceback (most recent call last):
  File "./Tools/autotest/autotest.py", line 437, in <module>
    util.pexpect_close_all()
  File "/home/grant/3dr/ardupilot/Tools/autotest/pysim/util.py", line 112, in pexpect_close_all
    pexpect_close(p)
  File "/home/grant/3dr/ardupilot/Tools/autotest/pysim/util.py", line 98, in pexpect_close
    p.close()
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 746, in close
    if not self.terminate(force):
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1139, in terminate
    time.sleep(self.delayafterterminate)

**Comment by gmorph** [comment]
This is working now.
