### ISSUE TITLE
SITL: wiki outdated, issues with ArduPlane

### ISSUE THREAD

**Issue by vmayoral** [diydrones/ardupilot#884]
I'm going through the SITL [installation instructions in the wiki](http://dev.ardupilot.com/wiki/setting-up-sitl-on-linux/). Step 6 instructions need to be updated. `sim_arduplane.sh` is not in the `ArduPlane` directory (but under `Tools/autotest`).

When running the first example in *step 6*:
```
../Tools/autotest/sim_arduplane.sh --console --map --aircraft test
+++ readlink -e ../Tools/autotest/sim_arduplane.sh
++ dirname /home/victor/ArduPilot/SITL/ardupilot/Tools/autotest/sim_arduplane.sh
+ autotest=/home/victor/ArduPilot/SITL/ardupilot/Tools/autotest
+ pushd /home/victor/ArduPilot/SITL/ardupilot/Tools/autotest/../../ArduPlane
~/ArduPilot/SITL/ardupilot/ArduPlane ~/ArduPilot/SITL/ardupilot/ArduPlane
+ '[' 0 == 1 ']'
+ make sitl -j4
HAL_BOARD=HAL_BOARD_AVR_SITL TOOLCHAIN=NATIVE EXTRAFLAGS=-DGIT_VERSION="63234d4c"
building /tmp/ArduPlane.build/ArduPlane.cpp
%% ArduPlane.cpp
+ cmd='/tmp/ArduPlane.build/ArduPlane.elf -I0'
+ '[' 0 == 1 ']'
+ '[' 0 == 1 ']'
+ /home/victor/ArduPilot/SITL/ardupilot/Tools/autotest/run_in_terminal_window.sh ardupilot /tmp/ArduPlane.build/ArduPlane.elf -I0
Starting ardupilot : /tmp/ArduPlane.build/ArduPlane.elf -I0
+ sleep 2
+ rm -f
+ /home/victor/ArduPilot/SITL/ardupilot/Tools/autotest/run_in_terminal_window.sh JSBSim ../Tools/autotest/jsbsim/runsim.py --home=-35.363261,149.165230,584,353 --simin=127.0.0.1:5502 --simout=127.0.0.1:5501 --fgout=127.0.0.1:5503
Starting JSBSim : ../Tools/autotest/jsbsim/runsim.py --home=-35.363261,149.165230,584,353 --simin=127.0.0.1:5502 --simout=127.0.0.1:5501 --fgout=127.0.0.1:5503
+ sleep 2
+ popd
~/ArduPilot/SITL/ardupilot/ArduPlane
+ mavproxy.py --master tcp:127.0.0.1:5760 --sitl 127.0.0.1:5501 --out 127.0.0.1:14550 --out 127.0.0.1:14551 --console --map --aircraft test
Traceback (most recent call last):
  File "/usr/local/bin/mavproxy.py", line 2058, in <module>
    m = mavutil.mavlink_connection(mdev, autoreconnect=True, baud=opts.baudrate)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 954, in mavlink_connection
    return mavtcp(device[4:], source_system=source_system)
  File "/usr/local/lib/python2.7/dist-packages/pymavlink/mavutil.py", line 788, in __init__
    self.port.connect(self.destination_addr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

Also note that the Xterm launched says:
```
/tmp/ArduPlane.build/ArduPlane.elf: invalid option -- 'I'
Unknown option '?'
```

This doesn't seem to happen with ArduCopter though.

**Comment by WickedShell** [comment]
Closing as the error this refers to no longer exsists/the documentation is correct at this point in time.
